# Etapa base: runtime de ASP.NET
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

# Etapa build: SDK para compilar
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copiar primero el archivo de proyecto
COPY ./src/Common/Common.csproj ./Common/
COPY ./src/Contracts/Contracts.csproj ./Contracts/
COPY ./src/ReleaseOrder/ReleaseOrder.csproj ./ReleaseOrder/
RUN dotnet restore ./ReleaseOrder/ReleaseOrder.csproj

# Copiar el resto del código
COPY ./src/Common ./Common
COPY ./src/Contracts ./Contracts
COPY ./src/ReleaseOrder ./ReleaseOrder
WORKDIR /src/ReleaseOrder
RUN dotnet publish -c Release -o /app/publish

# Etapa final: imagen ligera con el worker
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "ReleaseOrder.dll"]
