# Etapa base: runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

# Etapa build: SDK
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copiar primero los csproj para aprovechar caché
COPY ./src/Common/Common.csproj ./Common/
COPY ./src/Contracts/Contracts.csproj ./Contracts/
COPY ./src/OrderApi/OrderApi.csproj ./OrderApi/

# Restaurar dependencias
RUN dotnet restore ./OrderApi/OrderApi.csproj

# Copiar el resto del código
COPY ./src/Common ./Common
COPY ./src/Contracts ./Contracts
COPY ./src/OrderApi ./OrderApi

# Compilar y publicar
WORKDIR /src/OrderApi
RUN dotnet publish -c Release -o /app/publish

EXPOSE 5000
EXPOSE 5001


# Etapa final
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "OrderApi.dll"]